# Dcokerfile for go-gin-wrapper

FROM golang:1.7

RUN mkdir -p /go/src/github.com/hiromaily/go-questionnaires
RUN mkdir /var/log/questionnaire/


WORKDIR /go/src/github.com/hiromaily/go-gin-wrapper

#RUN go get -d -v ./... && go build -v -o /go/bin/questionnaires ./cmd/server/

EXPOSE 8880
