version: '3.0'

volumes:
  db: {}

services:
  # MySQL
  mysql:
    image: hirokiy/question-mysql:1.0
    container_name: question-mysql
    ports:
      - "${MYSQL_PORT:-4306}:3306"
    restart: always

  # Golang:api-server
  api:
    image: hirokiy/question-api:1.0
    container_name: question-api
    ports:
      - "${API_PORT:-8083}:8083"
    links:
      - mysql:mysql-server
    depends_on:
      - mysql
    stdin_open: true
    tty: true
    restart: always
    command: /go/bin/questionnaires -heroku 0

  # Nodejs:backoffice-server
  back-office:
    image: hirokiy/question-back:1.0
    container_name: question-backoffice
    ports:
      - "${BACK_PORT:-8082}:8082"
    stdin_open: true
    tty: true
    restart: always
    command: node ./app/server.js

  # Nodejs:frontoffice-server
  front-office:
    image: hirokiy/question-front
    container_name: question-frontoffice
    ports:
      - "${FRONT_PORT:-8081}:8081"
    stdin_open: true
    tty: true
    restart: always
    command: node ./app/server.js

  # Nginx
  nginx:
    image: hirokiy/question-nginx:1.0
    container_name: question-nginx
    ports:
      - "${NGINX_PORT:-8080}:80"
    links:
      - api:api-server
      - back-office:back-server
      - front-office:front-server
    depends_on:
      - api
      - back-office
      - front-office
    restart: always
